name: Update Website (local)

env:
  listPublishDirectory: Website
  pathToCi: ci
  indexLocation: "https://www.matthewherber.com/av3-animator-as-code/index.json"
  
on: 
  workflow_dispatch:
  workflow_run:
    workflows: [Build Release]
    types:
      - completed
  release:
     types: [published, edited, created, unpublished, deleted, released]
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-web:
    name: build-web
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # check out this repo
        with: 
          fetch-depth: 0 # fetch all history

      - uses: actions/checkout@v3 # check out automation repo
        with:
          #repository: vrchat-community/package-list-action
          repository: Happyrobot33/package-list-action #TODO: Change this to the main repo once it's merged
          path: ${{env.pathToCi}}
          clean: false # otherwise the local repo will no longer be checked out
          
      - name: Restore Timestamps
        uses: chetan/git-restore-mtime-action@v1

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            ${{env.pathToCi}}/.nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
          
      - name: Build Package Version Listing
        run: ${{env.pathToCi}}/build.cmd BuildMultiPackageListing --root ${{env.pathToCi}} --list-publish-directory $GITHUB_WORKSPACE/${{env.listPublishDirectory}} --current-listing-url ${{env.indexLocation}} --package-listing-source-filename sourcelocal.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{env.listPublishDirectory}}
          #path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
